"""Modification de prix_min et prix_max à prix

Revision ID: 63baabfff96d
Revises: 73840dd62eb6
Create Date: 2024-09-24 19:28:46.373752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63baabfff96d'
down_revision = '73840dd62eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_constraint('unique_listing', type_='unique')

    with op.batch_alter_table('search_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('price_max')
        batch_op.drop_column('price_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_min', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_max', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('price')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_listing', ['type', 'price', 'location'])

    # ### end Alembic commands ###
