"""Ajout de la colonne type

Revision ID: 6f4ded784831
Revises: 5676992fef6a
Create Date: 2024-09-19 12:12:51.506106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4ded784831'
down_revision = '5676992fef6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dbproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('dbproject_url_key', type_='unique')
        batch_op.drop_column('url')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dbproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('dbproject_url_key', ['url'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###
