"""Ajout de la relation entre utilisateurs et préférences de recherche, ajustement des types de données

Revision ID: 73840dd62eb6
Revises: 3b9764573d00
Create Date: 2024-09-24 16:16:13.449226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73840dd62eb6'
down_revision = '3b9764573d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=50),     
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using = "price::integer")

    with op.batch_alter_table('search_preferences', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_preferences', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
