"""Ajout de la relation User-SearchPreferences

Revision ID: 967fe269adbd
Revises: 6f4ded784831
Create Date: 2024-09-19 18:33:11.395669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967fe269adbd'
down_revision = '6f4ded784831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_preference')
    # ### end Alembic commands ###
