"""Ajout des champs title et description

Revision ID: a6be81930534
Revises: 63baabfff96d
Create Date: 2024-09-30 13:33:22.031393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6be81930534'
down_revision = '63baabfff96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('unique_listing', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_listing', ['type', 'price', 'location'])
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
